"""Stage 2 of the cascade: expand ECE abbreviations into full forms.

O*NET's title vocabulary is written by occupational analysts; a student writes
``RTL designer``. A search of release 30.3 returns zero rows for ``RTL``, so that
input is unreachable by any amount of string matching against the index. The
expansions in ``config/ece_abbreviation_expansions.yaml`` bridge the two
vocabularies.

Matching is on whole tokens of the raw input, case-insensitively, before
normalization -- ``SoC`` has to match ``soc`` and ``SOC`` alike, and doing it
pre-normalization keeps the acronym intact (normalization would strip the
trailing ``s`` off a hypothetical ``ICs``).

When more than one token expands, every combination is produced. The order is
fixed: variants are generated by iterating expansion lists in file order, left to
right across the input. That ordering is the only reason two runs of the cascade
return the same code set when several variants would each hit -- do not replace
it with a set or a dict comprehension over unordered input.
"""

from __future__ import annotations

import itertools
import re
from functools import lru_cache
from pathlib import Path

import yaml

from . import CONFIG_DIR

__all__ = [
    "EXPANSIONS_PATH",
    "load_expansions",
    "expand_tokens",
    "MAX_VARIANTS",
]

EXPANSIONS_PATH = CONFIG_DIR / "ece_abbreviation_expansions.yaml"

MAX_VARIANTS = 64
"""Cap on generated variants.

Three expandable tokens with two expansions each is already eight lookups; the
cap stops a pathological input from turning one resolution into thousands of
index probes. Truncation is deterministic because variant order is fixed.
"""

_TOKEN = re.compile(r"[A-Za-z0-9]+")


@lru_cache(maxsize=None)
def load_expansions(path: str | None = None) -> dict[str, tuple[str, ...]]:
    """Load the expansion table keyed by casefolded abbreviation."""
    target = Path(path) if path else EXPANSIONS_PATH
    raw = yaml.safe_load(target.read_text()) or {}
    table: dict[str, tuple[str, ...]] = {}
    for key, values in raw.items():
        if isinstance(values, str):
            values = [values]
        table[str(key).casefold()] = tuple(str(value) for value in values)
    return table


def expand_tokens(raw: str, expansions: dict[str, tuple[str, ...]] | None = None) -> tuple[str, ...]:
    """Return every expanded rewriting of ``raw``, excluding ``raw`` itself.

    ``"ML engineer"`` -> ``("Machine Learning engineer",)``.
    ``"RTL designer"`` -> ``("Register Transfer Level designer", "Digital Design designer")``.
    Returns ``()`` when no token is expandable.
    """
    table = expansions if expansions is not None else load_expansions()
    if not raw:
        return ()

    # Split into alternating literal / token pieces so the surrounding text is
    # preserved verbatim when a token is substituted.
    pieces: list[tuple[bool, str]] = []
    cursor = 0
    for match in _TOKEN.finditer(raw):
        if match.start() > cursor:
            pieces.append((False, raw[cursor : match.start()]))
        pieces.append((True, match.group()))
        cursor = match.end()
    if cursor < len(raw):
        pieces.append((False, raw[cursor:]))

    choices: list[tuple[str, ...]] = []
    any_expanded = False
    for is_token, text in pieces:
        if is_token:
            options = table.get(text.casefold())
            if options:
                any_expanded = True
                # The original token stays in play so that, with two expandable
                # tokens, partial expansions are tried as well as the full one.
                choices.append((*options, text))
                continue
        choices.append((text,))

    if not any_expanded:
        return ()

    variants: list[str] = []
    for combination in itertools.product(*choices):
        variant = "".join(combination)
        if variant != raw and variant not in variants:
            variants.append(variant)
        if len(variants) >= MAX_VARIANTS:
            break
    return tuple(variants)
