"""Acquire and pin the upstream source files, and expose readers for them.

Downloads each source into ``data/raw/`` and records ``url``, ``sha256``,
``retrieved_utc`` and ``release_label`` in ``data/raw/SOURCE_MANIFEST.yaml``.
Re-running verifies the hash of every file already present and skips the
download; a hash mismatch is a hard error, never a silent re-fetch.

This module is also the single place that knows how the raw bytes are laid out
-- which member of the O*NET zip holds job titles, which sheet of the crosswalk
holds CIP->SOC. Every downstream build script reads through the accessors here
rather than re-deriving those paths, so ``data/raw/`` stays untouched on disk.

Manual sources
--------------
``bls.gov`` refuses automated retrieval from most hosts (HTTP 403 with an
"Access Denied / bot activity" page on every path, including directory
listings). That is a transport refusal, not a missing release, so the SOC
structure file is registered as a manual source: the URL is recorded for
provenance, and the fetcher reports precise instructions instead of
substituting a different release.
"""

from __future__ import annotations

import hashlib
import io
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import requests
import yaml

from . import RAW_DIR

__all__ = [
    "SOURCES",
    "SourceFile",
    "MANIFEST_PATH",
    "MissingManifestEntry",
    "SourceHashMismatch",
    "ManualSourceMissing",
    "fetch_all",
    "raw_path",
    "read_manifest",
    "read_onet_table",
    "read_onet_readme",
    "read_all_occupations",
    "read_bls_soc_structure",
    "read_cip_soc_crosswalk",
    "main",
]

MANIFEST_PATH = RAW_DIR / "SOURCE_MANIFEST.yaml"

_ONET_RELEASE = "O*NET 30.3 Database (May 2026 Release)"
_USER_AGENT = "occupational-scrape/0.2 (degree-planning research; contact repository owner)"


class SourceHashMismatch(RuntimeError):
    """A file on disk does not match the sha256 pinned in the manifest."""


class MissingManifestEntry(RuntimeError):
    """A source has no manifest entry, so its bytes cannot be verified."""


class ManualSourceMissing(RuntimeError):
    """A manually-acquired source is not present in ``data/raw/``."""


@dataclass(frozen=True)
class SourceFile:
    key: str
    filename: str
    url: str
    release_label: str
    manual: bool = False
    manual_instructions: str = ""


SOURCES: tuple[SourceFile, ...] = (
    SourceFile(
        key="onet_database",
        filename="db_30_3_text.zip",
        url="https://www.onetcenter.org/dl_files/database/db_30_3_text.zip",
        release_label=_ONET_RELEASE,
    ),
    SourceFile(
        key="onet_all_occupations",
        filename="All_Occupations.csv",
        url="https://www.onetonline.org/find/all?fmt=csv",
        release_label="O*NET OnLine All Occupations export (site release 30.3)",
    ),
    SourceFile(
        key="bls_soc_structure",
        filename="soc_structure_2018.xlsx",
        url="https://www.bls.gov/soc/2018/soc_structure_2018.xlsx",
        release_label="BLS SOC 2018 structure",
        manual=True,
        manual_instructions=(
            "bls.gov returns HTTP 403 to automated clients from this host. Open\n"
            "  https://www.bls.gov/soc/2018/soc_structure_2018.xlsx\n"
            "in a browser and save it to data/raw/soc_structure_2018.xlsx, then\n"
            "re-run this script to hash and pin it."
        ),
    ),
    SourceFile(
        key="cip_soc_crosswalk",
        filename="CIP2020_SOC2018_Crosswalk.xlsx",
        url="https://nces.ed.gov/ipeds/cipcode/Files/CIP2020_SOC2018_Crosswalk.xlsx",
        release_label="NCES CIP 2020 to SOC 2018 Crosswalk",
    ),
)

_BY_KEY = {source.key: source for source in SOURCES}


# --------------------------------------------------------------------------
# Acquisition
# --------------------------------------------------------------------------


def raw_path(key: str) -> Path:
    """Absolute path of a registered source in ``data/raw/``."""
    return RAW_DIR / _BY_KEY[key].filename


def read_manifest() -> dict[str, dict]:
    if not MANIFEST_PATH.exists():
        return {}
    loaded = yaml.safe_load(MANIFEST_PATH.read_text()) or {}
    return {entry["key"]: entry for entry in loaded.get("sources", [])}


def _write_manifest(entries: dict[str, dict]) -> None:
    ordered = [entries[source.key] for source in SOURCES if source.key in entries]
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(
        "# Provenance record for data/raw/. Generated by fetch_source_files.py.\n"
        "# Hashes are pinned: a mismatch on re-run is a hard error, never a re-fetch.\n"
        + yaml.safe_dump({"sources": ordered}, sort_keys=False, default_flow_style=False)
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _download(source: SourceFile, destination: Path) -> None:
    response = requests.get(
        source.url, timeout=300, stream=True, headers={"User-Agent": _USER_AGENT}
    )
    if response.status_code == 404:
        raise RuntimeError(
            f"{source.key}: {source.url} returned 404. The pinned release is gone; "
            "stop and resolve this rather than substituting another release."
        )
    if response.status_code == 403:
        raise RuntimeError(
            f"{source.key}: {source.url} returned 403 (automated retrieval refused). "
            "Acquire the file manually and place it at "
            f"{destination}, then re-run."
        )
    response.raise_for_status()
    destination.parent.mkdir(parents=True, exist_ok=True)
    scratch = destination.with_suffix(destination.suffix + ".partial")
    with scratch.open("wb") as handle:
        for chunk in response.iter_content(1 << 20):
            handle.write(chunk)
    scratch.replace(destination)


def fetch_all(*, verify_only: bool = False) -> dict[str, dict]:
    """Download anything missing, verify everything present, return the manifest.

    Raises on any hash mismatch. Returns the manifest keyed by source key.
    """
    entries = read_manifest()
    deferred: list[str] = []
    for source in SOURCES:
        destination = raw_path(source.key)
        if not destination.exists():
            if source.manual:
                # Pin everything else first so a manual gap does not throw away
                # the provenance record for the sources that did arrive.
                deferred.append(
                    f"{source.key}: {destination} is missing and cannot be fetched "
                    f"automatically.\n{source.manual_instructions}"
                )
                continue
            if verify_only:
                raise ManualSourceMissing(
                    f"{source.key}: {destination} is missing (verify_only=True)."
                )
            print(f"[fetch] downloading {source.key} <- {source.url}")
            _download(source, destination)
        digest = _sha256(destination)
        recorded = entries.get(source.key)
        if recorded is None:
            entries[source.key] = {
                "key": source.key,
                "filename": source.filename,
                "url": source.url,
                "sha256": digest,
                "retrieved_utc": datetime.now(timezone.utc)
                .replace(microsecond=0)
                .isoformat()
                .replace("+00:00", "Z"),
                "release_label": source.release_label,
                "acquisition": "manual" if source.manual else "automatic",
            }
            print(f"[fetch] pinned {source.key} sha256={digest}")
        elif recorded["sha256"] != digest:
            raise SourceHashMismatch(
                f"{source.key}: {destination} has sha256 {digest}, manifest pins "
                f"{recorded['sha256']}. The upstream release changed or the file was "
                "edited. Resolve deliberately -- do not overwrite the manifest."
            )
        else:
            print(f"[fetch] verified {source.key} sha256={digest}")
    _write_manifest(entries)
    if deferred:
        raise ManualSourceMissing("\n\n".join(deferred))
    return entries


def require_manifest_entry(key: str) -> dict:
    entries = read_manifest()
    if key not in entries:
        raise MissingManifestEntry(
            f"{key} has no SOURCE_MANIFEST.yaml entry. Run fetch_source_files.py first."
        )
    return entries[key]


# --------------------------------------------------------------------------
# Readers -- the only sanctioned way to get at raw bytes
# --------------------------------------------------------------------------

ONET_TABLES = {
    "occupation_data": "Occupation Data.txt",
    "job_titles": "Job Titles.txt",
    "sample_of_reported_titles": "Sample of Reported Titles.txt",
}


def read_onet_table(name: str) -> pd.DataFrame:
    """Read one tab-delimited table straight out of the pinned O*NET zip."""
    member = ONET_TABLES[name]
    with zipfile.ZipFile(raw_path("onet_database")) as archive:
        candidates = [n for n in archive.namelist() if n.endswith("/" + member)]
        if not candidates:
            raise RuntimeError(f"{member} not present in the pinned O*NET archive")
        with archive.open(candidates[0]) as handle:
            return pd.read_csv(
                io.TextIOWrapper(handle, encoding="utf-8"),
                sep="\t",
                dtype=str,
                keep_default_na=False,
                na_values=[""],
            )


def read_onet_readme() -> str:
    with zipfile.ZipFile(raw_path("onet_database")) as archive:
        candidates = [n for n in archive.namelist() if n.lower().endswith("read me.txt")]
        if not candidates:
            return ""
        return archive.read(candidates[0]).decode("utf-8", errors="replace")


def read_all_occupations() -> pd.DataFrame:
    """The O*NET OnLine All Occupations export, the only source of ``Data-level``.

    ``Data-level`` marks whether O*NET publishes data for an occupation. Residual
    "All Other" buckets have it blank. The database bundle does not carry the
    column, which is why this export is pinned separately.
    """
    return pd.read_csv(
        raw_path("onet_all_occupations"), dtype=str, keep_default_na=False, na_values=[""]
    )


def read_bls_soc_structure() -> pd.DataFrame:
    """Parse the BLS SOC 2018 structure workbook into ``code``/``title``/``level``.

    The workbook has a preamble of title rows above a header row whose columns are
    the four level names plus a title column. The header row is located by content
    rather than by a fixed offset so a formatting change surfaces as a clear error
    instead of silently shifting every code by one row.
    """
    frame = pd.read_excel(raw_path("bls_soc_structure"), header=None, dtype=str)

    header_row = None
    for index, row in frame.iterrows():
        cells = [str(value).strip().casefold() for value in row.tolist() if pd.notna(value)]
        joined = " | ".join(cells)
        if "major group" in joined and "detailed occupation" in joined:
            header_row = index
            break
    if header_row is None:
        raise RuntimeError(
            "Could not locate the header row in the BLS SOC structure workbook. "
            "The layout changed; update read_bls_soc_structure rather than guessing."
        )

    header = [
        str(value).strip().casefold() if pd.notna(value) else ""
        for value in frame.iloc[header_row].tolist()
    ]
    level_columns: dict[str, int] = {}
    for position, name in enumerate(header):
        for level, marker in (
            ("major", "major group"),
            ("minor", "minor group"),
            ("broad", "broad group"),
            ("detailed", "detailed occupation"),
        ):
            if marker in name and level not in level_columns:
                level_columns[level] = position
    missing = {"major", "minor", "broad", "detailed"} - set(level_columns)
    if missing:
        raise RuntimeError(f"BLS structure workbook is missing level columns: {sorted(missing)}")

    # The title column sits immediately right of the four level columns and is
    # itself unlabelled in the header row, so it is located positionally.
    title_column = max(level_columns.values()) + 1
    if title_column >= frame.shape[1]:
        raise RuntimeError("BLS structure workbook has no title column after the level columns")

    records: list[dict[str, str]] = []
    for _, row in frame.iloc[header_row + 1 :].iterrows():
        values = row.tolist()
        title = values[title_column] if title_column < len(values) else None
        for level, column in level_columns.items():
            code = values[column] if column < len(values) else None
            if code is None or (isinstance(code, float) and pd.isna(code)):
                continue
            code = str(code).strip()
            if not code or code.casefold().startswith(("major", "minor", "broad", "detailed")):
                continue
            records.append(
                {
                    "code": code,
                    "title": ("" if title is None or pd.isna(title) else str(title).strip()),
                    "level": level,
                }
            )
    if not records:
        raise RuntimeError("Parsed zero rows from the BLS SOC structure workbook")
    return pd.DataFrame.from_records(records).drop_duplicates(subset=["code"], keep="first")


def read_cip_soc_crosswalk() -> pd.DataFrame:
    """The CIP-SOC sheet of the NCES crosswalk, columns renamed to snake_case."""
    frame = pd.read_excel(raw_path("cip_soc_crosswalk"), sheet_name="CIP-SOC", dtype=str)
    return frame.rename(
        columns={
            "CIP2020Code": "cip_code",
            "CIP2020Title": "cip_title",
            "SOC2018Code": "soc_code",
            "SOC2018Title": "soc_title",
        }
    )


def main() -> None:
    entries = fetch_all()
    print(f"\n{len(entries)} sources pinned in {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
