"""Diagnostic: how much of an ECE student's vocabulary the index actually covers.

Writes ``dev/reports/ece_title_coverage.md`` -- a human-readable report, which is
precisely why it lives in ``dev/`` and not in ``src/``. It answers two questions
that decide whether the abbreviation table is doing its job:

1. Which ECE terms return zero rows from a straight index lookup?
2. Of those, which are rescued by expansion, which by fuzzy match, and which
   remain unreachable without asking a model?

    PYTHONPATH=src python dev/inspect_ece_title_coverage.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from occupational_scrape.apply_career_backoff import apply_backoff, load_ece_leaf_set  # noqa: E402
from occupational_scrape.build_occupation_titles_index import load_title_index  # noqa: E402
from occupational_scrape.build_soc_hierarchy import load_soc_hierarchy  # noqa: E402
from occupational_scrape.expand_title_abbreviations import (  # noqa: E402
    expand_tokens,
    load_expansions,
)
from occupational_scrape.match_title_fuzzy import get_matcher  # noqa: E402
from occupational_scrape.normalize_job_title import normalize_title  # noqa: E402
from occupational_scrape.resolution_cache import ResolutionCache  # noqa: E402
from occupational_scrape.resolve_career_title import resolve_career_title  # noqa: E402

REPORT_PATH = REPO / "dev" / "reports" / "ece_title_coverage.md"

# Vocabulary an ECE student or a recruiter would actually use.
PROBES = [
    "computer hardware engineer",
    "electrical engineer",
    "electronics engineer",
    "embedded engineer",
    "embedded software engineer",
    "firmware engineer",
    "design verification engineer",
    "DV engineer",
    "RTL designer",
    "RTL design engineer",
    "ASIC engineer",
    "FPGA engineer",
    "VLSI engineer",
    "physical design engineer",
    "DFT engineer",
    "STA engineer",
    "analog design engineer",
    "mixed signal engineer",
    "RF engineer",
    "PCB designer",
    "SI engineer",
    "PI engineer",
    "power electronics engineer",
    "power systems engineer",
    "controls engineer",
    "DSP engineer",
    "signal processing engineer",
    "communications engineer",
    "network engineer",
    "SoC architect",
    "computer architect",
    "chip designer",
    "semiconductor engineer",
    "ML engineer",
    "MLE",
    "machine learning engineer",
    "AI engineer",
    "CV engineer",
    "NLP engineer",
    "data scientist",
    "HPC engineer",
    "GPU engineer",
    "robotics engineer",
    "mechatronics engineer",
    "photonics engineer",
    "MEMS engineer",
    "IoT engineer",
    "SWE",
    "software engineer",
    "hardware engineer",
    "EDA engineer",
    "PLC programmer",
    "test engineer",
    "systems engineer",
    "quant",
    "prompt engineer",
]


def main() -> None:
    index = load_title_index()
    matcher = get_matcher()
    hierarchy = load_soc_hierarchy()
    leaves = load_ece_leaf_set()
    expansions = load_expansions()

    # A throwaway cache: this is a diagnostic, it must not write to cache/.
    cache = ResolutionCache(REPO / "dev" / "reports" / ".coverage_scratch_cache.csv")
    if cache.path.exists():
        cache.path.unlink()

    rows = []
    for probe in PROBES:
        direct = index.lookup_raw(probe)
        variants = expand_tokens(probe)
        resolution = resolve_career_title(
            probe, index=index, matcher=matcher, cache=cache, use_llm=False
        )
        backed_off = apply_backoff(resolution, hierarchy=hierarchy, leaf_set=leaves)
        rows.append(
            {
                "probe": probe,
                "normalized": normalize_title(probe),
                "direct": direct,
                "variants": variants,
                "stage": resolution.stage,
                "codes": resolution.codes,
                "backoff": backed_off.backoff_level,
                "leaves": backed_off.codes,
            }
        )

    zero_direct = [row for row in rows if not row["direct"]]
    rescued_expanded = [row for row in zero_direct if row["stage"] == "expanded"]
    rescued_fuzzy = [row for row in zero_direct if row["stage"] == "fuzzy"]
    unreachable = [row for row in zero_direct if row["stage"] == "unmapped"]

    lines = [
        "# ECE title coverage in O*NET release 30.3",
        "",
        "Generated by `dev/inspect_ece_title_coverage.py`. Diagnostic only -- nothing",
        "in `src/` reads this file. Regenerate after bumping the O*NET release or",
        "editing `config/ece_abbreviation_expansions.yaml`.",
        "",
        "## Summary",
        "",
        f"- probes: **{len(rows)}**",
        f"- resolved by a direct index lookup (stage `exact`): **{len(rows) - len(zero_direct)}**",
        f"- zero direct hits: **{len(zero_direct)}**",
        f"  - rescued by abbreviation expansion: **{len(rescued_expanded)}**",
        f"  - rescued by fuzzy match: **{len(rescued_fuzzy)}**",
        f"  - still unreachable without the LLM stage: **{len(unreachable)}**",
        "",
        "The expansion table is carrying real weight here: every entry in the",
        "\"rescued by expansion\" list returns **zero** rows from a straight lookup",
        "against release 30.3 and would otherwise fall through to a model call or to",
        "elicitation.",
        "",
        "## Terms with zero direct index coverage",
        "",
        "| probe | expansions tried | stage reached | codes | backoff | ECE leaves |",
        "|---|---|---|---|---|---|",
    ]
    for row in zero_direct:
        variants = "<br>".join(row["variants"]) if row["variants"] else "_none_"
        codes = ", ".join(row["codes"]) if row["codes"] else "_none_"
        leaves_text = ", ".join(row["leaves"]) if row["leaves"] else "_none_"
        lines.append(
            f"| `{row['probe']}` | {variants} | `{row['stage']}` | {codes} | "
            f"`{row['backoff']}` | {leaves_text} |"
        )

    lines += [
        "",
        "## Full probe results",
        "",
        "| probe | normalized key | stage | codes | backoff level | ECE leaves after backoff |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        codes = ", ".join(row["codes"]) if row["codes"] else "_none_"
        leaves_text = ", ".join(row["leaves"]) if row["leaves"] else "_none_"
        lines.append(
            f"| `{row['probe']}` | `{row['normalized']}` | `{row['stage']}` | {codes} | "
            f"`{row['backoff']}` | {leaves_text} |"
        )

    lines += [
        "",
        "## Abbreviation table",
        "",
        f"{len(expansions)} keys are defined in `config/ece_abbreviation_expansions.yaml`.",
        "Keys whose acronym returns zero rows from a direct lookup (i.e. the expansion",
        "is the only path to a code):",
        "",
    ]
    for key in sorted(expansions):
        if not index.lookup_raw(key):
            lines.append(f"- `{key.upper()}` -> {', '.join(expansions[key])}")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n")
    if cache.path.exists():
        cache.path.unlink()

    print(f"wrote {REPORT_PATH}")
    print(f"  {len(zero_direct)}/{len(rows)} probes have zero direct index coverage")
    print(f"  expansion rescues {len(rescued_expanded)}, fuzzy rescues {len(rescued_fuzzy)}")
    print(f"  {len(unreachable)} remain unreachable without the LLM stage")


if __name__ == "__main__":
    main()
